type User {
  _id: ID!
  username: String!
  email: String!
  isActive: Boolean!
  isAdmin: Boolean!
}

input UserInput {
  username: String!
  email: String!
  password: String!
}

input resetPasswordInput {
  email: String!
  password: String!
  token: String!
}

type Query {
  getUsers: [User!]!
  getUser(id: ID): User!
}

type Mutation {
  createUser(data: UserInput): User!
  activeUser(id: ID!): User!
  disableUser(id: ID!): User!
  forgotPassword(credentials: String!): Boolean!
  resetPassword(data: resetPasswordInput): Boolean!
}
